services:
  mariadb:
    image: "mariadb"
    restart: 'always'
    volumes:
      - "/var/lib/mysql/data:/home/ubuntu/.datasql"
      - "/var/lib/mysql/logs:/home/ubuntu/.logssql"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "testrootpw"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "testpw"
  wordpress:
    image: "wordpress-datascientest"
    build: ./wordpress
    ports:
        - 8030:80
